// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Penthertz <https://penthertz.com> (https://x.com/PentHertz)

//! Raw FFI bindings to FUSE-T's libfuse 2.x-compatible C API.
//!
//! Most of this file is the `include!()` of `OUT_DIR/bindings.rs`,
//! generated by `build.rs` via bindgen against `<fuse_t/fuse.h>`.
//! Hand-written declarations below cover symbols bindgen can't see
//! through the libfuse macros (chiefly `fuse_main_real` which is
//! defined as a macro that wraps `fuse_main_real_versioned`), and
//! the few libfuse-private types we touch directly.
//!
//! Anything `pub use`d from here is a raw FFI surface; the safe
//! wrapper lives in `ops.rs`. Don't `unsafe extern "C"` from outside
//! this module.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(non_upper_case_globals)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// `fuse_main_real` is the canonical libfuse 2.x entry point. It
// handles arg parsing, mount, signal handlers, and the event loop in
// one call. bindgen sees it through the `fuse_main(...)` macro that
// expands to `fuse_main_real(... , sizeof(struct fuse_operations))`,
// re-declare it explicitly so we can call it without the macro.
//
// Signature per `fuse.h` (libfuse 2.9):
//   int fuse_main_real(int argc, char *argv[],
//                      const struct fuse_operations *op,
//                      size_t op_size, void *user_data);
unsafe extern "C" {
    pub fn fuse_main_real(
        argc: ::core::ffi::c_int,
        argv: *mut *mut ::core::ffi::c_char,
        op: *const fuse_operations,
        op_size: usize,
        user_data: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;

    /// libfuse 2.x ABI version probe. Returns `MAJOR * 10 + MINOR`,
    /// e.g. 29 for libfuse 2.9. FUSE-T's compat layer reports the
    /// libfuse version it emulates, which we want to be `>= 29`.
    /// Used by `ops::run_mount` for a startup ABI sanity check.
    pub fn fuse_version() -> ::core::ffi::c_int;
}
