// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Penthertz <https://penthertz.com> (https://x.com/PentHertz)

//! Raw FFI bindings to FUSE-T's libfuse 2.x-compatible C API.
//!
//! Most of this file is the `include!()` of `OUT_DIR/bindings.rs`,
//! generated by `build.rs` via bindgen against `<fuse_t/fuse.h>`.
//! Hand-written declarations below cover symbols bindgen can't see
//! through the libfuse macros (chiefly `fuse_main_real` which is
//! defined as a macro that wraps `fuse_main_real_versioned`), and
//! the few libfuse-private types we touch directly.
//!
//! Anything `pub use`d from here is a raw FFI surface; the safe
//! wrapper lives in `ops.rs`. Don't `unsafe extern "C"` from outside
//! this module.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(non_upper_case_globals)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// NOTE: an earlier version of this file hand-declared
// `fuse_main_real` and `fuse_version` here because libfuse 2.x
// historically exposes them only behind the `fuse_main()` /
// `FUSE_MAJOR_VERSION` macros (which bindgen can't see through).
// FUSE-T's `<fuse_t/fuse.h>` declares both functions directly in
// the public header, so bindgen picks them up and includes them in
// the generated `bindings.rs`. Hand-declaring them here would
// duplicate-define the symbols and fail to compile (E0428). We
// rely on the bindgen output exclusively. If a future libfuse-t
// release hides one of these behind a macro again, restore the
// hand-decl below it (with appropriate cfg guards if needed).
